name: prettier check

on:
  push:
    branches: [main]
    paths: ["admin/**", "package.json", "yarn.lock", "turbo.json", "front/src/lib/**"]
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    paths: ["admin/**", "package.json", "yarn.lock", "turbo.json", "front/src/lib/**"]

defaults:
  run:
    working-directory: admin

jobs:
  prettier:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install
        run: yarn install --frozen-lockfile
      - name: prettier
        run: yarn prettier --check src
