// Copies the self-hosted fonts into fonts/ and writes fonts/fonts.css (dev only, output committed):
//   node scripts/build-fonts.mjs
// Barlow, Barlow Semi Condensed and JetBrains Mono, SIL OFL 1.1, via @fontsource. Only the latin and
// latin-ext subsets (English and Polish), only the weights the page uses. Nothing is loaded from Google Fonts.
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const out = join(dirname(fileURLToPath(import.meta.url)), "..", "fonts");
mkdirSync(out, { recursive: true });

const FAMILIES = [
  { pkg: "barlow", family: "Barlow", weights: [300, 400, 500] },
  { pkg: "barlow-semi-condensed", family: "Barlow Semi Condensed", weights: [400, 500, 600] },
  { pkg: "jetbrains-mono", family: "JetBrains Mono", weights: [400, 500] },
];
const RANGES = {
  latin: "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
  "latin-ext": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF",
};

let css = "/* Generated by scripts/build-fonts.mjs. Barlow, Barlow Semi Condensed and JetBrains Mono: SIL OFL 1.1. */\n";
let licences = "";
for (const { pkg, family, weights } of FAMILIES) {
  const dir = dirname(require.resolve(`@fontsource/${pkg}/package.json`));
  licences += `${family}\n${readFileSync(join(dir, "LICENSE"), "utf8")}\n\n`;
  for (const weight of weights) {
    for (const subset of ["latin", "latin-ext"]) {
      const file = `${pkg}-${subset}-${weight}-normal.woff2`;
      copyFileSync(join(dir, "files", file), join(out, file));
      css += `@font-face{font-family:'${family}';font-style:normal;font-display:swap;font-weight:${weight};src:url(${file}) format('woff2');unicode-range:${RANGES[subset]}}\n`;
    }
  }
}
writeFileSync(join(out, "fonts.css"), css);
writeFileSync(join(out, "OFL.txt"), licences.trim() + "\n");
console.log("fonts written to", out);
