#!/usr/bin/env node
// Endpoint coverage (plan 4.10): every operation of spec/openapi.json must be covered by a command
// (`endpoints`) or excluded in spec/exclusions.yaml with a reason. `ulams api` does not count.
// Writes coverage/matrix.json and coverage/matrix.md; exits 1 on gaps or stale entries.
import { spawnSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync, existsSync, appendFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parse as parseYaml } from "yaml";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const REASONS = ["inbound-webhook", "browser-only", "content-runtime", "internal", "deprecated", "not-for-cli"];
const METHODS = ["get", "post", "put", "patch", "delete"];

const spec = JSON.parse(readFileSync(resolve(root, "spec/openapi.json"), "utf8"));
const exclusions = parseYaml(readFileSync(resolve(root, "spec/exclusions.yaml"), "utf8")) ?? {};

const dist = resolve(root, "dist/ulams.mjs");
if (!existsSync(dist)) {
  console.error("Build first: yarn workspace ulams build");
  process.exit(1);
}
const run = spawnSync("node", [dist, "schema", "--json"], { encoding: "utf8", maxBuffer: 64 * 1024 * 1024, env: { ...process.env, ULAMS_CONFIG_DIR: resolve(root, ".docs-config") } });
if (run.status !== 0) {
  console.error(run.stderr || run.stdout);
  process.exit(1);
}
const registry = JSON.parse(run.stdout).data;

const operations = [];
for (const [path, item] of Object.entries(spec.paths)) {
  for (const m of METHODS) if (item[m]) operations.push({ key: `${m.toUpperCase()} ${path}`, summary: (item[m].summary ?? "").trim() });
}
const opKeys = new Set(operations.map((o) => o.key));

const covered = new Map();
const problems = [];
const undocumented = [];
for (const cmd of registry.commands) {
  for (const e of cmd.endpoints) {
    if (!opKeys.has(e)) problems.push(`${cmd.id} lists ${e}, which is not in spec/openapi.json (use \`undocumented\` for routes the spec lacks)`);
    else if (!covered.has(e)) covered.set(e, cmd.id);
  }
  for (const e of cmd.undocumented) undocumented.push({ endpoint: e, command: cmd.id });
}

// exclusions: { reason: [ "METHOD /path" | "* /path/prefix*" ] }
const excluded = new Map();
const usedEntries = new Set();
for (const [reason, entries] of Object.entries(exclusions)) {
  if (!REASONS.includes(reason)) problems.push(`exclusions.yaml: unknown reason "${reason}" (allowed: ${REASONS.join(", ")})`);
  for (const entry of entries ?? []) {
    const [m, p] = String(entry).split(" ");
    const star = p?.endsWith("*");
    let hit = 0;
    for (const o of operations) {
      const [om, op] = o.key.split(" ");
      if ((m === "*" || m === om) && (star ? op.startsWith(p.slice(0, -1)) : op === p)) {
        if (!excluded.has(o.key)) excluded.set(o.key, reason);
        hit++;
      }
    }
    if (hit === 0) problems.push(`exclusions.yaml: "${entry}" matches no operation`);
    usedEntries.add(entry);
  }
}
for (const key of excluded.keys()) if (covered.has(key)) problems.push(`${key} is both covered (${covered.get(key)}) and excluded`);

const rows = operations.map((o) => {
  if (covered.has(o.key)) return { ...o, command: covered.get(o.key), status: "covered" };
  if (excluded.has(o.key)) return { ...o, command: "", status: `excluded: ${excluded.get(o.key)}` };
  return { ...o, command: "", status: "missing" };
});
const missing = rows.filter((r) => r.status === "missing");
for (const r of missing) problems.push(`not covered and not excluded: ${r.key}`);

const summary = `${rows.filter((r) => r.status === "covered").length}/${rows.length} covered, ${excluded.size} excluded, ${missing.length} missing, ${undocumented.length} routes missing from the spec`;
mkdirSync(resolve(root, "coverage"), { recursive: true });
writeFileSync(resolve(root, "coverage/matrix.json"), `${JSON.stringify({ summary, operations: rows, undocumented }, null, 1)}\n`);
const md = [
  "# CLI endpoint coverage",
  "",
  "Generated by `yarn workspace ulams coverage` from `spec/openapi.json`, the command registry and `spec/exclusions.yaml`. Do not edit.",
  "",
  `**${summary}.**`,
  "",
  "| Operation | Command | Status |",
  "|---|---|---|",
  ...rows.map((r) => `| \`${r.key}\` | ${r.command ? `\`${r.command}\`` : ""} | ${r.status} |`),
  "",
  "## Routes missing from the OpenAPI spec",
  "",
  "These routes exist and have commands, but the API's OpenAPI document does not describe them yet.",
  "",
  "| Route | Command |",
  "|---|---|",
  ...undocumented.map((u) => `| \`${u.endpoint}\` | \`${u.command}\` |`),
  "",
].join("\n");
writeFileSync(resolve(root, "coverage/matrix.md"), md);
console.log(`coverage: ${summary}`);
if (process.env.GITHUB_STEP_SUMMARY) appendFileSync(process.env.GITHUB_STEP_SUMMARY, `CLI endpoint coverage: ${summary}\n`);
if (problems.length) {
  for (const p of problems) console.error(`- ${p}`);
  console.error(`coverage: ${problems.length} problem(s)`);
  process.exit(1);
}
