import { sharedTheme } from "./shared";
import type { ThemeTokens } from "./types";

/**
 * Presets for the three demo e-learning experiences described in
 * front/docs/design/experiences.md. Colours follow the Stitch design briefs.
 */

/**
 * "The Coffee Atlas": warm editorial, paper canvas, serif display type.
 * Values follow the Stitch design system (front/docs/design/stitch/DESIGN.md).
 */
export const coffeeTheme: ThemeTokens = {
  ...sharedTheme,
  theme: "coffee",
  mode: "light",
  font: "Playfair Display",
  bodyFont: "Plus Jakarta Sans",
  radius: 4,
  buttonRadius: 4,
  inputRadius: 4,
  checkboxRadius: 2,
  noteRadius: 4,
  cardRadius: 4,
  modalRadius: 4,
  primaryColor: "#C2552D",
  dm__primaryColor: "#E07A52",
  secondaryColor: "#7A8B6F",
  dm__secondaryColor: "#9DB08F",
  headerColor: "#2B1D14",
  dm__headerColor: "#F6F1E9",
  textColor: "#2B1D14",
  dm__textColor: "#F6F1E9",
  background: "#F6F1E9",
  dm__background: "#1E1611",
  cardBackgroundColor: "#EDE5D8",
  dm__cardBackgroundColor: "#2B1D14",
  colorBackground: "#C2552D",
  dm__colorBackground: "#A84521",
  inputBg: "#FDFCFA",
  dm__inputBg: "#2B1D14",
  gray5: "#FDFCFA",
  gray4: "#EDE5D8",
  gray3: "#D9CFC2",
  gray2: "#6B5750",
  gray1: "#57423B",
  labelListValueColor: "#C2552D",
  breadcrumbsColor: "#7A8B6F",
  outlineButtonColor: "#2B1D14",
  dm__outlineButtonColor: "#F6F1E9",
};

/** "On-Call": dense, dark, pro-tool look with semantic signal colours. */
export const oncallTheme: ThemeTokens = {
  ...sharedTheme,
  theme: "oncall",
  mode: "dark",
  font: "Space Grotesk",
  bodyFont: "Inter",
  radius: 4,
  buttonRadius: 4,
  inputRadius: 4,
  cardRadius: 6,
  modalRadius: 6,
  primaryColor: "#1F6FEB",
  dm__primaryColor: "#58A6FF",
  dm__primaryColorOnLight: "#1F6FEB",
  secondaryColor: "#3FB950",
  headerColor: "#0B0F14",
  dm__headerColor: "#E6EDF3",
  textColor: "#0B0F14",
  dm__textColor: "#E6EDF3",
  background: "#F6F8FA",
  dm__background: "#0B0F14",
  cardBackgroundColor: "#FFFFFF",
  dm__cardBackgroundColor: "#121821",
  colorBackground: "#121821",
  dm__colorBackground: "#121821",
  errorColor: "#CF222E",
  dm__errorColor: "#F85149",
  invertColor: "#D29922",
  positive: "#3FB950",
  positive2: "#12261E",
  gray5: "#F6F8FA",
  gray4: "#E6EDF3",
  gray3: "#8B98A5",
  gray2: "#1E2733",
  gray1: "#121821",
  inputBg: "#FFFFFF",
  dm__inputBg: "#0B0F14",
  outlineButtonColor: "#0B0F14",
  dm__outlineButtonColor: "#E6EDF3",
  // Disabled buttons in dark mode (e.g. "Back" on the first lesson). Before the
  // CSS-variable migration this value leaked in from the orange preset's defaults.
  dm__primaryButtonDisabled: "#6D6D6D",
};

/** "Night Sky Explorers": playful, rounded, night blue with bright accents. */
export const nightskyTheme: ThemeTokens = {
  ...sharedTheme,
  theme: "nightsky",
  mode: "dark",
  font: "Baloo 2",
  bodyFont: "Inter",
  radius: 16,
  buttonRadius: 24,
  inputRadius: 16,
  checkboxRadius: 6,
  cardRadius: 20,
  modalRadius: 24,
  noteRadius: 16,
  primaryColor: "#5B4BDB",
  dm__primaryColor: "#FFD23F",
  dm__primaryColorOnLight: "#5B4BDB",
  secondaryColor: "#FF6B6B",
  dm__secondaryColor: "#FF6B6B",
  headerColor: "#13153A",
  dm__headerColor: "#FFFFFF",
  textColor: "#13153A",
  dm__textColor: "#F2F0FF",
  background: "#F2F0FF",
  dm__background: "#13153A",
  cardBackgroundColor: "#FFFFFF",
  dm__cardBackgroundColor: "#1F2257",
  colorBackground: "#9B8CFF",
  dm__colorBackground: "#2A2E73",
  positive: "#3DDC97",
  positive2: "#D6F8E9",
  invertColor: "#FFD23F",
  gray5: "#F2F0FF",
  gray4: "#E3DFFF",
  gray3: "#B7B0E8",
  gray2: "#6A66A3",
  gray1: "#2A2E73",
  outlineButtonColor: "#13153A",
  dm__outlineButtonColor: "#FFD23F",
  // See oncallTheme: formerly leaked in from the orange preset's defaults.
  dm__primaryButtonDisabled: "#6D6D6D",
};
