/** Valid props for every builder component, shaped like what the API streams. */
const cite = (n: number) => ({ fragmentId: `frg_aaaaaaaaaaa${n}`, label: `§${n} Section ${n}` });
const counts = (n: number) => ({ courses: n, lessons: n, topics: n, questions: n, pages: n });

export const builderFixtures: Record<string, Record<string, unknown>> = {
  Column: { gap: "md" },
  Text: { text: "I read your handbook.", variant: "body" },
  ChoiceChips: {
    questionKey: "assessments",
    label: "How should learners check their progress?",
    why: "Short quizzes help learners remember the key numbers.",
    status: "open",
    step: 5,
    total: 6,
    options: [
      { value: "quiz", label: "Quiz after each lesson" },
      { value: "final", label: "Final test" },
    ],
    multiple: true,
    allowCustom: false,
    defaultValue: ["quiz"],
  },
  SingleChoice: {
    questionKey: "level",
    label: "What level should it start at?",
    status: "open",
    options: [
      { value: "beginner", label: "Beginner" },
      { value: "intermediate", label: "Intermediate" },
      { value: "advanced", label: "Advanced" },
    ],
    defaultValue: "beginner",
  },
  DurationSlider: {
    questionKey: "duration",
    label: "How long should the course be?",
    status: "open",
    totalOptions: [30, 60, 120],
    lessonOptions: [5, 10, 15],
    defaultValue: { totalMinutes: 60, lessonMinutes: 10 },
  },
  LanguagePicker: {
    questionKey: "language",
    label: "Which language should the course use?",
    status: "answered",
    decidedBy: "default",
    options: [
      { value: "en", label: "English" },
      { value: "pl", label: "Polski" },
    ],
    value: "en",
    defaultValue: "en",
  },
  DecideForMe: { label: "Decide the rest for me", open: 3 },
  SourceCard: {
    sourceId: "01src",
    name: "coffee-brewing.md",
    status: "ready",
    sizeBytes: 6400,
    tokens: 3900,
    fragmentCount: 22,
    sections: [{ fragmentId: "frg_aaaaaaaaaaa1", label: "§1.1 What extraction means", level: 1 }],
  },
  CitationChip: cite(1),
  OutlineDiff: {
    versionId: "01v",
    number: 1,
    status: "proposed",
    editable: true,
    targetMinutes: 30,
    summary: { modules: 1, lessons: 1, minutes: 10, objectives: 2 },
    course: { title: "Coffee Brewing Fundamentals", objectives: [{ id: "o0", text: "Brew a balanced cup", change: "added", citations: [cite(1)] }] },
    modules: [
      {
        id: "m1",
        title: "Extraction",
        change: "added",
        lessons: [{ id: "l1", title: "What extraction means", minutes: 10, change: "added", objectives: [{ id: "o1", text: "Explain extraction", citations: [cite(1)] }], citations: [cite(1)] }],
      },
    ],
    removed: [],
  },
  GenerationProgress: {
    runId: "01run",
    status: "needs_attention",
    stages: [
      { key: "lessons", label: "Lessons", status: "running" },
      { key: "quizzes", label: "Quizzes", status: "pending" },
    ],
    lessons: [
      { id: "l1", title: "1.1 What extraction means", module: "Extraction", status: "done", citations: 3, questions: 2, costMicroUsd: 30000 },
      { id: "l2", title: "1.2 Strength", module: "Extraction", status: "failed", stepId: "01step", error: "The model declined this step." },
    ],
    cost: { usedMicroUsd: 120000, budgetMicroUsd: 5000000, inputTokens: 1000, outputTokens: 400, cacheReadTokens: 3000 },
  },
  LessonPreviewCard: {
    lessonId: "l1",
    title: "What extraction means",
    minutes: 10,
    blocks: [
      { id: "b1", kind: "paragraph", markdown: "Brewing is **extraction**. <script>alert(1)</script>", citations: [cite(1)] },
      { id: "b2", kind: "table", markdown: "| A | B |\n|---|---|\n| 1 | 2 |", citations: [cite(2)] },
    ],
    flags: [],
  },
  QuizQuestionCard: {
    questionId: "q1",
    type: "single",
    stem: "How much water for 20 g of coffee at 1:16?",
    options: [
      { id: "a", text: "300 ml", correct: false },
      { id: "b", text: "320 ml", correct: true },
    ],
    explanation: "20 × 16 = 320.",
    citations: [cite(2)],
  },
  DiffView: {
    versionId: "01p",
    elementId: "q1",
    elementLabel: "Lesson 2.1 › Q2",
    reason: "Make the distractors less obvious",
    status: "proposed",
    changes: [{ path: "a.text", label: "Option A · Text", kind: "changed", before: "350 ml", after: "310 ml" }],
    citations: [cite(2)],
  },
  ApplySummary: { versionId: "01c", status: "proposed", firstApply: true, create: counts(1), update: counts(0), delete: counts(0), warnings: ["Lesson 1.2: Possibly unsupported claim"] },
  VersionList: {
    currentVersionId: "v3",
    versions: [
      { id: "v2", number: 2, kind: "content", origin: "ai", status: "approved", reason: "Generated lessons" },
      { id: "v3", number: 3, kind: "patch", origin: "ai", status: "approved", reason: "Shorter" },
      { id: "v4", number: 4, kind: "update", origin: "ai", status: "approved", reason: "Source update r1 → r2: 3 changes" },
    ],
  },
  SourceConnectionCard: {
    sourceId: "01src",
    name: "coffee-brewing.md",
    kind: "markdown",
    connector: "upload",
    state: "new_version",
    syncedRevision: 1,
    latestRevision: 2,
    lastCheckedAt: "2026-10-20T09:30:00+00:00",
    schedule: "manual",
    error: "The last upload could not be read.",
    canCheck: true,
    canUpload: true,
  },
  RevisionTimeline: {
    sourceId: "01src",
    selectedRevisionId: "01rev2",
    revisions: [
      {
        id: "01rev2",
        number: 2,
        origin: "upload",
        trigger: "manual",
        detectedAt: "2026-10-20T09:30:00+00:00",
        status: "ingested",
        counts: { changed: 3, moved: 1, removed: 1, added: 2, trivial: 0, minor: 4, substantive: 3, total: 7 },
        synced: false,
        latest: true,
      },
      { id: "01rev1", number: 1, origin: "initial", trigger: "initial", detectedAt: "2026-10-19T09:30:00+00:00", status: "ingested", synced: true, latest: false },
    ],
  },
  FragmentChange: {
    changeId: "7",
    kind: "changed",
    magnitude: "substantive",
    similarity: 0.82,
    signals: ["number"],
    section: "Brewing ratios",
    old: { fragmentId: "frg_aaaaaaaaaaa1", label: "§2.3 Brewing ratios", text: "Use 15 g of coffee for 250 g of water." },
    new: { fragmentId: "frg_aaaaaaaaaaa2", label: "§2.3 Brewing ratios", text: "Use 16 g of coffee for 250 g of water." },
    wordDiff: [
      ["=", "Use "],
      ["-", "15"],
      ["+", "16"],
      ["=", " g of coffee for 250 g of water."],
    ],
  },
  UpdateItem: {
    itemId: "01item1",
    elementId: "q1",
    elementType: "question",
    label: "Lesson 2.1 › Q2",
    kind: "update",
    status: "pending",
    reason: "Section 2.3 now recommends 1:16 instead of 1:15.",
    severity: "major",
    sources: "Based on §2.3 Brewing ratios",
    fields: [
      { path: "stem", label: "Question", before: "How much water for 15 g of coffee?", after: "How much water for 16 g of coffee?" },
      { path: "options.o3", label: "Option C (correct)", before: "225 g", after: "256 g" },
    ],
    citations: [cite(2)],
    flags: ["Possibly unsupported: the water must be filtered"],
    signals: ["number"],
    answerCheck: true,
    answerChanged: true,
    regenerations: 1,
    maxRegenerations: 3,
    canDecide: true,
    canRegenerate: true,
    href: "/studio/s/01s/workspace",
  },
  ImpactSummary: {
    elements: 6,
    answerChecks: 2,
    uncovered: 1,
    remaps: 3,
    major: 2,
    lessons: 3,
    estimatedCostMicroUsd: 420000,
    costMicroUsd: 130000,
    learnerImpact: "12 learners completed lesson 2.",
  },
  StalenessBadge: { state: "stale", days: 3, pendingElements: 4, href: "/studio/s/01s/updates" },
  CostMeter: { usedMicroUsd: 710000, budgetMicroUsd: 5000000, tokens: 120000, label: "Sonnet" },
  LearnerImpact: { applied: false, noticesOff: false, topicUpdated: 12, questionReattempt: 3, topicRetired: 1, courseExtended: 0 },
  AuditTable: {
    caption: "Audit trail of this course, newest first",
    emptyText: "No entries match these filters.",
    entries: [
      {
        id: 12,
        at: "2026-10-20T10:15:00+00:00",
        action: "proposal.applied",
        actionLabel: "Update applied",
        actorType: "user",
        actor: "Ada Lovelace",
        summary: "Applied 5 accepted changes as version r1 to r2.",
        details: [
          { label: "Source revision", value: "Revision 2 (upload)" },
          { label: "Course version", value: "v3 to v4" },
          { label: "AI calls", value: "2" },
          { label: "Hash", value: "9f2c1d0e8b7a", mono: true },
          { label: "Previous hash", value: "03ab44c1e5d2", mono: true },
        ],
      },
      { id: 11, at: "2026-10-20T10:10:00+00:00", action: "item.accepted", actionLabel: "Change accepted", actorType: "user", actor: "Ada Lovelace", summary: "Lesson 1.1, paragraph 1." },
      { id: 10, at: "2026-10-20T09:31:00+00:00", action: "revision.detected", actionLabel: "New source revision", actorType: "system", actor: "System", summary: "Revision 2 of coffee-brewing.md.", details: [] },
    ],
  },
};
