# Used by BuildKit for `docker build -f front/Dockerfile .` (context = repo root)
.git
**/node_modules
**/dist
**/.turbo
**/.env
**/.env.*
!**/.env.example
api
!api/package.json
admin
!admin/package.json
front/android
front/ios
front/stats.html
