version: "3.8"

volumes:
  frontend-node-modules: ~

services:
  build:
    image: node:22-alpine
    volumes:
      - ../:/srv/app
      - frontend-node-modules:/srv/app/node_modules/
    working_dir: /srv/app/front
    command: "sh -c 'yarn &&  yarn build'"
