<?php

namespace Ulams\TemplatesPdf\Http\Controllers\Swagger;

use Ulams\TemplatesPdf\Http\Requests\PdfListingRequest;
use Ulams\TemplatesPdf\Http\Requests\PdfReadRequest;
use Ulams\TemplatesPdf\Http\Requests\PdfListingAdminRequest;
use Ulams\TemplatesPdf\Http\Requests\PdfPreviewRequest;
use Symfony\Component\HttpFoundation\Response;

use Illuminate\Http\JsonResponse;

interface FabricPdfControllerSwagger
{
    /**
     * @OA\Get(
     *      path="/api/pdfs",
     *      summary="Get generated PDFs",
     *      tags={"Template PDFs"},
     *      description="Get paginated list of PDFs generated by templates",
     *      security={
     *         {"passport": {}},
     *      },
     *      @OA\Parameter(
     *          name="page",
     *          description="Pagination Page Number",
     *          required=false,
     *          in="query",
     *          @OA\Schema(
     *              type="number",
     *               default=1,
     *          ),
     *      ),
     *      @OA\Parameter(
     *          name="per_page",
     *          description="Pagination Per Page",
     *          required=false,
     *          in="query",
     *          @OA\Schema(
     *              type="number",
     *               default=15,
     *          ),
     *      ),
     *      @OA\Parameter(
     *           name="assignable_type",
     *           description="Assignable type (Ulams\Courses\Models\Course)",
     *           required=false,
     *           in="query",
     *           @OA\Schema(
     *               type="string"
     *           )
     *      ),
     *      @OA\Parameter(
     *            name="assignable_id",
     *            description="Assignable ID",
     *            required=false,
     *            in="query",
     *            @OA\Schema(
     *                type="integer"
     *            )
     *      ),
     *      @OA\Response(
     *          response=200,
     *          description="successful operation",
     *          @OA\MediaType(
     *              mediaType="application/json"
     *          ),
     *          @OA\Schema(
     *              type="object",
     *              @OA\Property(
     *                  property="success",
     *                  type="boolean"
     *              ),
     *              @OA\Property(
     *                  property="data",
     *                  type="array",
     *                  @OA\Items(ref="#/components/schemas/FabricPDF")
     *              ),
     *              @OA\Property(
     *                  property="message",
     *                  type="string"
     *              )
     *          )
     *      )
     * )
     */
    public function index(PdfListingRequest $request): JsonResponse;

    /**
     * @OA\Get(
     *      path="/api/pdfs/{id}",
     *      summary="Display the specified generated PDF",
     *      tags={"Template PDFs"},
     *      description="Get generated PDF",
     *      security={
     *         {"passport": {}},
     *      },
     *      @OA\Parameter(
     *          name="id",
     *          description="id of generated PDF",
     *          @OA\Schema(
     *             type="integer",
     *         ),
     *          required=true,
     *          in="path"
     *      ),
     *      @OA\Response(
     *          response=200,
     *          description="successful operation",
     *          @OA\MediaType(
     *              mediaType="application/json"
     *          ),
     *          @OA\Schema(
     *              type="object",
     *              @OA\Property(
     *                  property="success",
     *                  type="boolean"
     *              ),
     *              @OA\Property(
     *                  property="data",
     *                  ref="#/components/schemas/FabricPDF"
     *              ),
     *              @OA\Property(
     *                  property="message",
     *                  type="string"
     *              )
     *          )
     *      )
     * )
     */
    public function show(PdfReadRequest $request, int $id): JsonResponse;

    /**
     * @OA\Get(
     *      path="/api/admin/pdfs",
     *      summary="Display the specified generated PDF",
     *      tags={"Admin Template PDFs"},
     *      description="Get generated PDF, IF user_id or template_id is provided all records are returned, otherwise list is paginated ",
     *      security={
     *         {"passport": {}},
     *      },
     *      @OA\Parameter(
     *          name="user_id",
     *          description="either user_id",
     *          @OA\Schema(
     *             type="integer",
     *         ),
     *          in="query"
     *      ),
     *      @OA\Parameter(
     *          name="template_id",
     *          description="or user_id",
     *          @OA\Schema(
     *             type="integer",
     *         ),
     *          in="query"
     *      ),
     *      @OA\Response(
     *          response=200,
     *          description="successful operation",
     *          @OA\MediaType(
     *              mediaType="application/json"
     *          ),
     *          @OA\Schema(
     *              type="object",
     *              @OA\Property(
     *                  property="success",
     *                  type="boolean"
     *              ),
     *              @OA\Property(
     *                  property="data",
     *                  ref="#/components/schemas/FabricPDF"
     *              ),
     *              @OA\Property(
     *                  property="message",
     *                  type="string"
     *              )
     *          )
     *      )
     * )
     */
    public function admin(PdfListingAdminRequest $request): JsonResponse;

    /**
     * @OA\Get(
     *      path="/api/pdfs/generate/{id}",
     *      summary="Download a generated PDF (certificate)",
     *      tags={"Template PDFs"},
     *      description="Returns the stored PDF, or renders it from its pdfme template and variables through the PDF renderer service",
     *      security={
     *         {"passport": {}},
     *      },
     *      @OA\Parameter(
     *          name="id",
     *          description="id of the generated PDF",
     *          @OA\Schema(
     *             type="integer",
     *         ),
     *          required=true,
     *          in="path"
     *      ),
     *      @OA\Response(
     *          response=200,
     *          description="successful operation",
     *          @OA\MediaType(
     *              mediaType="application/pdf"
     *          )
     *      ),
     *      @OA\Response(response=422, description="legacy (ReportBro) or invalid template"),
     *      @OA\Response(response=503, description="PDF renderer unavailable")
     * )
     */
    public function generate(PdfReadRequest $request, int $id): Response;

    /**
     * @OA\Post(
     *      path="/api/admin/pdfs/preview",
     *      summary="Preview a pdfme template with sample data",
     *      tags={"Template PDFs"},
     *      description="Renders a pdfme template (unsaved designer content) with the mocked variables of the event, through the PDF renderer service",
     *      security={
     *         {"passport": {}},
     *      },
     *      @OA\RequestBody(
     *          required=true,
     *          @OA\JsonContent(
     *              required={"event", "content"},
     *              @OA\Property(property="event", type="string", example="Ulams\\Courses\\Events\\CourseFinished"),
     *              @OA\Property(property="content", description="pdfme template (object or JSON string)", type="object"),
     *          )
     *      ),
     *      @OA\Response(
     *          response=200,
     *          description="successful operation",
     *          @OA\MediaType(
     *              mediaType="application/pdf"
     *          )
     *      ),
     *      @OA\Response(response=403, description="no template create/update permission"),
     *      @OA\Response(response=422, description="invalid template or unknown event")
     * )
     */
    public function preview(PdfPreviewRequest $request): Response;

    /**
     * @OA\Get(
     *      path="/api/pdfs/fonts",
     *      summary="Fonts available in PDF templates",
     *      tags={"Template PDFs"},
     *      description="Fonts bundled with the PDF renderer (SIL OFL); the admin designer loads them from /api/pdfs/fonts/{file}",
     *      @OA\Response(response=200, description="successful operation")
     * )
     */
    public function fonts(): JsonResponse;

    /**
     * @OA\Get(
     *      path="/api/pdfs/fonts/{file}",
     *      summary="Font file used in PDF templates",
     *      tags={"Template PDFs"},
     *      @OA\Parameter(name="file", in="path", required=true, @OA\Schema(type="string", example="NotoSans-Regular.ttf")),
     *      @OA\Response(response=200, description="successful operation", @OA\MediaType(mediaType="font/ttf")),
     *      @OA\Response(response=404, description="unknown font")
     * )
     */
    public function font(string $file): Response;
}
