FROM escolalms/php:8.3-alpine
WORKDIR /var/www/html
EXPOSE 9000
COPY / /var/www/html
# pecl.php.net is unreliable (504) - build excimer from GitHub source instead
RUN cd /tmp && curl -fsSL -o excimer.tgz https://codeload.github.com/wikimedia/mediawiki-php-excimer/tar.gz/refs/tags/1.2.7 \
  && tar xzf excimer.tgz && cd php-excimer-1.2.7 && phpize && ./configure && make && make install \
  && cd /tmp && rm -rf excimer.tgz php-excimer-1.2.7
RUN \
  cp docker/conf/supervisor/supervisord.conf /etc/supervisord.conf \
  && cp docker/conf/php/ulams-custom-php.ini /usr/local/etc/php/conf.d/ulams-custom-php.ini \  
  && cp docker/conf/php/ulams-custom-develop-php.ini /usr/local/etc/php/conf.d/ulams-custom-develop-php.ini \  
  && cp docker/conf/php/php-fpm-custom.conf /usr/local/etc/php-fpm.d/php-fpm-custom.conf
RUN composer install --no-scripts --no-dev

CMD /var/www/html/init.sh

HEALTHCHECK --interval=30s --timeout=30s --start-period=10s --retries=5 CMD [ "php", "artisan", "health:check" ]